# Generated by Django 3.1.3 on 2020-12-20 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField()),
                ('startTimezone', models.CharField(max_length=10)),
                ('endTime', models.DateTimeField()),
                ('endTimezone', models.CharField(max_length=10)),
                ('price', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sight',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.event')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(null=True)),
            ],
            bases=('core.event',),
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.event')),
                ('transferType', models.CharField(max_length=100)),
                ('departurePoint', models.TextField(null=True)),
                ('arrivalPoint', models.TextField(null=True)),
                ('number', models.CharField(max_length=30, null=True)),
            ],
            bases=('core.event',),
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField()),
                ('Timezone', models.CharField(max_length=10)),
                ('endTime', models.DateTimeField()),
                ('price', models.PositiveIntegerField(null=True)),
                ('name', models.CharField(max_length=100)),
                ('room', models.CharField(max_length=100, null=True)),
                ('address', models.TextField(null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.trip')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.trip'),
        ),
    ]
